import type { DashboardJob } from "@/modules/dashboard/types";

export const dashboardJobs: DashboardJob[] = [
	{
		id: "figma-product-designer",
		title: "Product Designer",
		company: "Figma",
		location: "San Francisco, CA",
		workMode: "Remote",
		jobType: "Full-time",
		source: {
			name: "Company Site",
			url: "https://www.figma.com/careers/job/product-designer",
			faviconUrl: "https://www.google.com/s2/favicons?domain=figma.com&sz=64",
		},
		appliedDate: "May 20, 2025",
		reminder: "May 27",
		status: "Applied",
		brand: "figma",
	},
	{
		id: "vercel-frontend-developer",
		title: "Frontend Developer",
		company: "Vercel",
		location: "New York, NY",
		workMode: "Hybrid",
		jobType: "Full-time",
		source: {
			name: "Company Site",
			url: "https://vercel.com/careers/frontend-developer",
			faviconUrl: "https://www.google.com/s2/favicons?domain=vercel.com&sz=64",
		},
		appliedDate: "May 18, 2025",
		reminder: "May 26",
		status: "Interview",
		brand: "vercel",
	},
	{
		id: "airbnb-data-analyst",
		title: "Data Analyst",
		company: "Airbnb",
		location: "Austin, TX",
		workMode: "Remote",
		jobType: "Full-time",
		source: {
			name: "LinkedIn",
			url: "https://www.linkedin.com/jobs/view/airbnb-data-analyst",
			faviconUrl:
				"https://www.google.com/s2/favicons?domain=linkedin.com&sz=64",
		},
		appliedDate: "May 15, 2025",
		reminder: "May 29",
		status: "Applied",
		brand: "airbnb",
	},
	{
		id: "hubspot-business-development",
		title: "Business Development Executive",
		company: "HubSpot",
		location: "Boston, MA",
		workMode: "On-site",
		jobType: "Full-time",
		source: {
			name: "LinkedIn",
			url: "https://www.linkedin.com/jobs/view/hubspot-business-development",
			faviconUrl:
				"https://www.google.com/s2/favicons?domain=linkedin.com&sz=64",
		},
		appliedDate: "May 14, 2025",
		reminder: "-",
		status: "Saved",
		brand: "hubspot",
	},
	{
		id: "notion-ux-researcher",
		title: "UX Researcher",
		company: "Notion",
		location: "San Francisco, CA",
		workMode: "Remote",
		jobType: "Contract",
		source: {
			name: "Company Site",
			url: null,
			faviconUrl: "https://www.google.com/s2/favicons?domain=notion.so&sz=64",
		},
		appliedDate: "May 12, 2025",
		reminder: "May 23",
		status: "Interview",
		brand: "notion",
	},
	{
		id: "spotify-marketing-manager",
		title: "Marketing Manager",
		company: "Spotify",
		location: "New York, NY",
		workMode: "Hybrid",
		jobType: "Full-time",
		source: {
			name: "LinkedIn",
			url: "https://www.linkedin.com/jobs/view/spotify-marketing-manager",
			faviconUrl:
				"https://www.google.com/s2/favicons?domain=linkedin.com&sz=64",
		},
		appliedDate: "May 10, 2025",
		reminder: "-",
		status: "Rejected",
		brand: "spotify",
	},
	{
		id: "linear-product-manager",
		title: "Product Manager",
		company: "Linear",
		location: "Remote",
		workMode: "Worldwide",
		jobType: "Full-time",
		source: {
			name: "Manual",
			url: null,
			faviconUrl: null,
		},
		appliedDate: "May 9, 2025",
		reminder: "May 21",
		status: "Interview",
		brand: "linear",
	},
	{
		id: "calendly-customer-success",
		title: "Customer Success Specialist",
		company: "Calendly",
		location: "Atlanta, GA",
		workMode: "Hybrid",
		jobType: "Full-time",
		source: {
			name: "Indeed",
			url: "https://www.indeed.com/viewjob?jk=calendly-customer-success",
			faviconUrl: "https://www.google.com/s2/favicons?domain=indeed.com&sz=64",
		},
		appliedDate: "May 8, 2025",
		reminder: "May 22",
		status: "Offer",
		brand: "calendly",
	},
	{
		id: "plaid-software-engineer",
		title: "Software Engineer",
		company: "Plaid",
		location: "San Francisco, CA",
		workMode: "Hybrid",
		jobType: "Full-time",
		source: {
			name: "Company Site",
			url: "https://plaid.com/careers/software-engineer",
			faviconUrl: "https://www.google.com/s2/favicons?domain=plaid.com&sz=64",
		},
		appliedDate: "May 6, 2025",
		reminder: "-",
		status: "Saved",
		brand: "plaid",
	},
	{
		id: "canva-content-designer",
		title: "Content Designer",
		company: "Canva",
		location: "Sydney, Australia",
		workMode: "Remote",
		jobType: "Contract",
		source: {
			name: "Company Site",
			url: "https://www.canva.com/careers/content-designer",
			faviconUrl: "https://www.google.com/s2/favicons?domain=canva.com&sz=64",
		},
		appliedDate: "May 5, 2025",
		reminder: "-",
		status: "Offer",
		brand: "canva",
	},
];

export const dashboardStats = [
	{ label: "Total Jobs", value: "42", trend: "12% this month" },
	{ label: "Applied", value: "18", trend: "8% this month" },
	{ label: "Interview", value: "4", trend: "2% this month" },
	{ label: "Offers", value: "1", trend: "1% this month" },
	{ label: "Rejected", value: "10", trend: "3% this month" },
];

export const analyticsMonthlyActivity = ["Feb", "Mar", "Apr", "May", "Jun", "Jul"];
